### ISSUE TITLE
Rendering issue after Episerver.CMS.Core 12.17.0 upgrade 

### ISSUE THREAD

**Issue by Niiilsen** [Geta/geta-optimizely-contenttypeicons#14]
After upgrading Episerver.CMS.Core to version 12.17.0, Geta.Optimizely.ContentTypeIcons no longer works, (thumbnail generation fails).

According to [this blog post](https://world.optimizely.com/blogs/son-d--nguyen/dates/2023/8/a-note-on-cms-core-12-17-0-upgrade/): 

> As of today, EPiServer.CMS.Core relies on SixLabors ImageSharp v2 to do image manipulations under the hood. There have been quite a few [WEBP issues](https://world.optimizely.com/support/Bug-list/bug/CMS-27466) being raised lately, which have their root in this library. In order to fix them, we need to upgrade the library to v3. But there are binary incompatible changes between v2 and v3. For partners, who also use ImageSharp v2 directly in their code base, this upgrade could be a breaking change.

> We move the image service's implementation to a separate package, EPiServer.ImageLibrary.ImageSharp, and release it independently from CMS Core. There are two major versions of the package. v1 of the package depends on ImageSharp v2, and v2 of the package depends on ImageSharp v3. You are encouraged to use v2 unless ImageSharp API is consumed directly in your code.

the issue is that Episerver.CMS.Core now relies on a SixLabors ImageSharp v3 or higher, which has breaking changes that causes and causes Geta.Optimizely.ContentTypeIcons to fail. 

Will there be a fix for this in the nearest future?

**Comment by ArjanX** [comment]
I found the same issue. I fixed it myself with the Geta codebase. I can do a PR if anyone is interested?
Alternatively you can have my dll.

**Comment by Niiilsen** [comment]
@ArjanX I might end up doing so myself if no fix is provided, but I'm in no rush so i'll wait a few weeks and see. 
If you already fixed it probably won't hurt to create a PR, maybe that speeds up the process! :)

**Comment by ArjanX** [comment]
@Niiilsen it appears I'm not allowed to create a branch.. but yeah, it's simple fixes.

**Comment by marisks** [comment]
@ArjanX You can fork the repository, make changes, and create a pull request. After the review, we will release the new version.

**Comment by ArjanX** [comment]
> @ArjanX You can fork the repository, make changes, and create a pull request. After the review, we will release the new version.

Yep thanks, I think I got it. See PR. Sorry not that familiar with GH.

**Comment by Niiilsen** [comment]
@marisks I see the PR from @ArjanX was approved and that latest release contains the fix for this issue. Will the [nuget](https://nuget.optimizely.com/package/?id=Geta.Optimizely.ContentTypeIcons) package be updated any time soon? :)

**Comment by marisks** [comment]
Just uploaded the new version. Should be available soon.
