### ISSUE TITLE
Unable to load font fa5/webfonts/fa-regular-400.ttf from EmbeddedResource

### ISSUE THREAD

**Issue by lars-w-pedersen** [Geta/geta-optimizely-contenttypeicons#2]
I have added the nuget package "Geta.Optimizely.ContentTypeIcons" Version="1.0.0-rc"
i call services.AddContentTypeIcons(); in Startup
and on my PageType i have this Attribute: [ContentTypeIcon(FontAwesome5Regular.Folder)]

When i in Optimizely try to create a new page this url is called:
https://localhost:5000/Geta_Optimizely_ContentTypeIcons?BackgroundColor=%2302423F&ForegroundColor=%23ffffff&Width=120&Height=90&FontSize=40&Character=61563&CustomFontName=&EmbeddedFont=fa5%2fwebfonts%2ffa-regular-400.ttf&UseEmbeddedFont=True&Rotate=None

i returns this error:

System.Exception: Unable to load font fa5/webfonts/fa-regular-400.ttf from EmbeddedResource
 ---> System.IO.FileNotFoundException: The file /ClientResources/fa5/webfonts/fa-regular-400.ttf does not exist.
   at Microsoft.Extensions.FileProviders.NotFoundFileInfo.CreateReadStream()
   at Geta.Optimizely.ContentTypeIcons.ContentTypeIconService.LoadFontFamilyFromClientResources(String fileName)

I realized that the module is not installed with the nuget package so i got Geta.Optimizely.ContentTypeIcons.zip from the sandbox and added it to modules/_protected but that just changed the error slightly:

System.Exception: Unable to load font fa5/webfonts/fa-regular-400.ttf from EmbeddedResource
 ---> System.IO.FileNotFoundException: The file /EPiServer/Geta.Optimizely.ContentTypeIcons/ClientResources/fa5/webfonts/fa-regular-400.ttf does not exist.
   at Microsoft.Extensions.FileProviders.NotFoundFileInfo.CreateReadStream()
   at Geta.Optimizely.ContentTypeIcons.ContentTypeIconService.LoadFontFamilyFromClientResources(String fileName)

**Comment by LucGosso** [comment]
I do have the same issue .. @marisks  Any idea? seems to be in the zip package ... Can it be rights? or format? can we use woff2 ?

**Comment by marisks** [comment]
Could you try package 1.0.0-rc2? It is on nuget.optimizely.com (it is not listed as it is pre-release)

**Comment by LucGosso** [comment]
oh, i did have that one

![image](https://user-images.githubusercontent.com/9716195/140269018-5f2be47e-ae46-4c9b-bb0d-09f904e094e7.png)

**Comment by marisks** [comment]
And after you build your project, does the ZIP file exist in modules/_protected/Geta.Optimizely.ContentTypeIcons ?

**Comment by LucGosso** [comment]
yes

**Comment by LucGosso** [comment]
FI: Im NOT runing .net5 thru IIS

**Comment by marisks** [comment]
Just tried on a fresh Alloy site and am getting the same results. Will check what is happening.

**Comment by marisks** [comment]
I have pushed the new version - 1.0.0-rc3. It might take some time while it become available.

**Comment by LucGosso** [comment]
Works good with rc3, thanks Maris!
