### ISSUE TITLE
Breaks Swagger

### ISSUE THREAD

**Issue by ViktorBergman** [Geta/geta-optimizely-contenttypeicons#5]
Geta.Optimizely.ContentTypeIcons version 1.0.0 breaks Swagger when using Swashbuckle.AspNetCore 6.2.3

`SwaggerGeneratorException: Ambiguous HTTP method for action - Geta.Optimizely.ContentTypeIcons.Controllers.ContentTypeIconController.Index (Geta.Optimizely.ContentTypeIcons). Actions require an explicit HttpMethod binding for Swagger/OpenAPI 3.0`

**Comment by marisks** [comment]
I have installed Swashbuckle.AspNetCore 6.2.3 into the project and everything works fine (see latest sandbox/Alloy example).
Do you have a sample project that has the issue?

P.S. `ContentTypeIconController` is not API controller, but MVC controller. Swagger should not try generating API documentation for it.
