### ISSUE TITLE
No Tree icons after update to 2.0.1

### ISSUE THREAD

**Issue by Dandroid5000** [Geta/geta-optimizely-contenttypeicons#7]
Hi,
I just updated from 1.0.0 to 2.0.1 and all my tree icons have dissapeared (they were showing before). I have not changed any configs (i.e. EnableTreeIcons is still set to true). 
The thumbnails are still working ok (at least on my local instance; I have not yet tested in DXP).
I'm not seeing any errors logged (to the server logs or browser console).
Has anyone else come across this?
Any suggestions?
Thanks in advance
Dan

**Comment by marisks** [comment]
I will take a look

**Comment by Dandroid5000** [comment]
Thanks @marisks ! Appreciate it!

**Comment by marisks** [comment]
@Dandroid5000 I just tried on the Sandbox site and everything works. In the latest version, I have updated fonts to the latest version. Maybe some icons were removed? What icons are you using?

**Comment by Dandroid5000** [comment]
OK, thanks for confirming. 

Here's some examples:
FontAwesome5Solid.Newspaper
FontAwesome.Hotel
FontAwesome5Solid.Bookmark
FontAwesome5Solid.UserNinja
FontAwesome5Solid.Search

^ none of those are working. We have a lot more too... and none of those are working either.

**Comment by marisks** [comment]
I found the issue that might cause it for you.
In the latest version, you have to call `UseContentTypeIcons` in the `Configure` method of the `Startup`. This is the new way how to initialize things.
I have updated readme (forgot to do it).

**Comment by Dandroid5000** [comment]
Yep. That was the issue! 
Thank so much for your quick replies and thanks again for this great package.
Will close this one.
Have a great day!
Cheers
Dan
